---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bookinfo-schedule
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: bookinfo-chaos
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: bookinfo-chaos
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: bookinfo-chaos
          restartPolicy: Never
          containers:
          - name: chaostoolkit
            image: mgndocker/chaostoolkit:latest
            args:
            - --verbose
            - run
            - --journal-path
            - /results/journal-bookinfo-abort.json
            - /experiment/bookinfo-abort.yaml
            env:
            - name: CHAOSTOOLKIT_IN_POD
              value: "true"
            - name: INGRESS_HOST
              value: "34.73.137.113"
            volumeMounts:
            - name: experiments
              mountPath: /experiment
              readOnly: true
            - name: results
              mountPath: /results
              readOnly: false
            resources:
              limits:
                cpu: 20m
                memory: 64Mi
              requests:
                cpu: 20m
                memory: 64Mi
          volumes:
          - name: experiments
            configMap:
              name: bookinfo-config
          - name: results
            persistentVolumeClaim:
              claimName: bookinfo-chaos
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookinfo-chaos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

