---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-chaos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookinfo-chaos
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - pods
  - deployments
  - jobs
  verbs:
  - list
  - get
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  verbs:
  - list
  - get
  - create
  - delete
  - update
  - patch
  - watch
- apiGroups:
  - "networking.istio.io"
  resources:
  - "virtualservices"
  verbs:
  - list
  - get
  - create
  - delete
  - update
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bookinfo-chaos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bookinfo-chaos
subjects:
  - kind: ServiceAccount
    name: bookinfo-chaos
    namespace: default
